os: Visual Studio 2015
environment:
  matrix:
  - CLI_VERSION: 1.0.0-rc4-004842
  - CLI_VERSION: Latest

matrix:
  allow_failures:
    - CLI_VERSION: Latest

install:
  - ps: .\scripts\show-dotnet-info.ps1
  - ps: mkdir -Force ".\scripts\obtain\" | Out-Null
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1" -OutFile ".\scripts\obtain\install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\scripts\obtain\install.ps1 -Channel preview -version "$env:CLI_VERSION" -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  - mkdir artifacts
  - ps: .\scripts\show-dotnet-info.ps1
  - dotnet --info
  - dotnet restore
  - dotnet build -v n
  - dotnet pack /p:Version=%appveyor_build_version% -o artifacts -c Release Coral.Core\Coral.Core.csproj

test_script:
  - ps: dotnet test Coral.Core.Test/Coral.Core.Test.csproj

artifacts:
  - path: artifacts\**\*.nupkg
    name: NuGet

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/coral/api/v2/package
    api_key:
      secure: b5oBmcZl3AXKVJ/lzr6SFRUqgUXK8V8rGmFTiIFp70UMZmuOzyJa6x/l0UTIaElq
    skip_symbols: true
    on:
      branch: master

version: 0.1.0-b{build}
