os: Visual Studio 2015
environment:
  matrix:
  - CLI_VERSION: 1.0.0-rc4-004842
  - CLI_VERSION: Latest

matrix:
  allow_failures:
    - CLI_VERSION: Latest

install:
  - ps: .\scripts\show-dotnet-info.ps1
  - ps: mkdir -Force ".\scripts\obtain\" | Out-Null
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1" -OutFile ".\scripts\obtain\install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\scripts\obtain\install.ps1 -Channel preview -version "$env:CLI_VERSION" -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  - ps: .\scripts\show-dotnet-info.ps1
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet build -v n

test: off
version: 1.0.0-b{build}